project:
  type: website
  output-dir: docs

website:
  title: 'Oliver Jones'
  sidebar:
    style: docked
    search: true
    contents: 
      - section: 'About Me'
        contents: 
          - index.qmd
          - About.qmd
      - section: 'My Work'
        contents: 
          - quarto.qmd
          - text: 'Data Engineering Experience'
            file: Data_eng.qmd
          - text: 'Data Visualisation Experience'
            file: Data_vis.qmd

format: 
  html: 
    theme: darkly
    