project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: docked
    search: true
    contents: 
      - section: 'About Me'
        contents: 
          - index.qmd
          - About.qmd
      - section: 'My Work'
        contents: 
          - quarto.qmd

format: 
  html: 
    theme: darkly
    