# Work Experience

## Current: NHS England - BI developer
2021 - Present

Business Intelligence developer focused on building visualisation products to be used to support
decision making for healthcare professionals to improve patient experience.

My responsibilities include:

- End to end Tableau development (stakeholder engagement, requirements & design, data sourcing, dashboard build, UAT & handover to stakeholders)
- Improve Tableau development operating model - this includes setting up systems and processes for collecting requirements that can be used to improve developers efficiency.
- Data pipeline build in python on Azure
- Run visualisation tool proof of concepts to expand the offering of the team (currently looking at using Streamlit and other web app tools to display data to users)

Tools used:

- Tableau
- SQL
- Python
- Azure

## Previous: HSBC - SENIOR GLOBAL FINANCE CHANGE BI DEVELOPER
2016 - 2021

Data developer and analyst on a project focused on migrating legacy financial reporting systems onto Google Cloud.

My responsibilities include:

- SQL development with several different Google scrums involving converting SAS jobs to run on Google and uplifting current Google BigQuery SQLs/workflows. Experience with development of several concurrent code branches managed with JIRA & GitHub.
- Creation and integration of data workflows to allow two large reporting batches to run as one integrated batch.
- Batch monitoring and troubleshooting using Google logging tools.
- Data management including data sourcing using SFTP & Hadoop to migrate data from On-premise systems to Google Cloud, building & maintaining table schemas and creating extracts
- Coordinating deployments from GitHub to UAT/Production environments using Jenkins
- Data model and dashboard build using Tableau for a range of MI products
- Stakeholder support during UAT/transition to investigate and resolve any bugs that arise
- Application SME for the migration from On-premise SAS to Google Cloud – Guided Google specific design issues, coordinating code/environment integration and managing the technical side of UAT.
- Reporting Framework PoC – This included building a tool in Appian to capture reporting framework requirements. I was responsible for the design of the back end data model and build in Appian
- End user tool testing – Configuration and user testing of workflow management tool, adjustment tool and validation frameworks.
- Mentoring and training of junior team members

Tools used:

- Tableau
- SQL
- SAS
- Google cloud
- Shell scripting
- Hadoop